#!/bin/sh

. /etc/network/qemu-if.conf

restart_dhcp="no"

echo "$0:"
echo "Setting up the network bridge for $1"
if brctl addbr "$BRIDGE"; then
	echo "restart dhcp service"
	restart_dhcp="yes"
fi
brctl addif "$BRIDGE" "$1"
ifconfig "$BRIDGE" "$HOST" netmask "$MASK"
ip link set "$1" up
ip link set "$BRIDGE" up

if [ "$restart_dhcp" = "yes" ]; then
        echo "starting dhcp service $?"
        service isc-dhcp-server start

fi

if iptables -t nat -L POSTROUTING -n | grep ^MASQUERADE | awk '{print $4}' | cut -d/ -f1 | grep "$NETWORK" >/dev/null
then
  echo "IP masquerading already set up"
else
  echo "Setting up IP masquerading"
  iptables -t nat -A POSTROUTING -s "$NETWORK"/"$MASK" -d ! "$NETWORK"/"$MASK" -j MASQUERADE
fi

echo "Setting up IP forwarding"
sysctl net.ipv4.ip_forward=1

exit 0
