#!/bin/sh

. /etc/network/qemu-if.conf

echo "$0:"
service isc-dhcp-server stop
echo "Tearing down network bridge for $1"
ip link set $1 down
brctl delif "$BRIDGE" $1

ifconfig kvmnat 0.0.0.0
ip link set "$BRIDGE" down
brctl delbr "$BRIDGE"

exit 0
