#!/bin/sh

#===============================================================================
# System
#===============================================================================

# Mount /etc/fstab
mount -t proc proc /proc
mount -t sysfs sysfs /sys

#Create all the symlinks to /bin/busybox
busybox --install -s

#Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

#===============================================================================
# System
#===============================================================================
# Set hostname
hostname "bakka"

export PS1='[\u@\h \W]\$ '
/bin/sh
